# Generated by Django 3.2.7 on 2021-10-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='parent_box',
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
