# Generated by Django 3.2.7 on 2021-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_favourite',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='box',
            name='files_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
