# Generated by Django 3.2.7 on 2021-10-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
