# Generated by Django 3.2.7 on 2021-10-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
