# Generated by Django 3.2.7 on 2021-10-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='parent_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_boxes', to='api.box'),
        ),
    ]
