# Generated by Django 3.2.7 on 2021-10-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_file_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='extension',
        ),
    ]
