# Generated by Django 3.2.7 on 2021-10-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_file_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='item',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
