# Generated by Django 3.2.7 on 2021-10-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_box_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='size',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
