# Generated by Django 3.2.7 on 2021-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211008_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='instance',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
