# Generated by Django 3.2.7 on 2021-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_file_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='files_count',
            field=models.IntegerField(default=0),
        ),
    ]
