# Generated by Django 3.2.7 on 2021-09-28 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellibox_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default=0, max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
    ]
