# Generated by Django 3.2.7 on 2021-10-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellibox_auth', '0002_user_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_limit',
            field=models.PositiveBigIntegerField(default=2147483648),
        ),
        migrations.AddField(
            model_name='user',
            name='storage_used',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
